@FMLab.Aspnet.CleanArchitecture.Api_HostAddress = http://localhost:9000
@ApiKey = e6ae77d8-95b0-4627-b6b9-aa2a56b78474

POST {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users
Content-Type: application/json
X-Api-Key: {{ApiKey}}

{
  "name": "Jon Doe",
  "email": "john.doe@email.com"
}

###

GET {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users?page=1&pageSize=2
X-Api-Key: {{ApiKey}}

###

GET {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users/1
X-Api-Key: {{ApiKey}}

###

POST {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users/1/deactivate
X-Api-Key: {{ApiKey}}

###

GET {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users?status=Deactivated
X-Api-Key: {{ApiKey}}

###

GET {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users?status=Active
X-Api-Key: {{ApiKey}}

###

PATCH {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users/1
Content-Type: application/json
X-Api-Key: {{ApiKey}}
{
  "name": "John Doe"
}

###

PUT {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users/1
Content-Type: application/json
X-Api-Key: {{ApiKey}}
{
  "name": "John Doe"
}

###

DELETE {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/Users/1
X-Api-Key: {{ApiKey}}